def calculate_potions(creature_sequence):
    potion_requirements = {
        'A': 0,  
        'B': 1,  
        'C': 3  
    }
    
    total_potions = 0
    
    for creature in creature_sequence:
        if creature in potion_requirements:
            total_potions += potion_requirements[creature]  
        else:
            print(f"Warning: Creature '{creature}' not recognized!")

    return total_potions

creature_sequence = "BCCBCBACCBBBAACACCAAACCCACCCBCBABABCCCACCBAABCCAABABBAAAACCAABAAABBAAACABCBCCAABAAABABACACBBACBCCAABAABBABCBACBACABBABACABBAABAAAAAACACCACABBAACBBAAACCBCACCACBAACAAABACACBACCCBCCBCCCAACCBABCBCABABCBABAABACBBBABCBBCCAACCAABBABCCCACCCCCCBAACACBCCBAACCBBCCABBACCBBCCCCCCCAACBACABBAAACACBBAACBCCABCABCBCCCACCACBCABAABBBCCACABCCBCAABBCCAACCBABBCCCCAAAABABABBBBBCBCBCBCCABCABCCACBBABBAACBCCABBABCCBCABCABCACBBAAABCCBCBBABAACBBCCBBBCACBCAABCACCBABACCABABCCAACACBCBBABACBCABCBBABAAAAACABCBACCCACCBBBBAACACCAABAABABBCACCACCCACCACCABBCBBABBCBACBCACABCAABCCBCBCBBABABAAACCACCAAABBBBCBCBAABAABBCCBAABABCABCCCCABBACCBBCCCBBCAABABBCCBCACBABAABBCBABCABCCCAAABACCACBCABCCCAACABCCBBCAABCCBAABABBACCCCABABCABABACAABAACACABBBCCCACBACBBCBCAACCCAACBABBBCACAAAABCAAACBABCCCBACCBAABCABCCCCBCBBAACAAAABBACABBBCBABBCACBABCCAACAAABBAAABABBACCCCABBABCBABBBCCABBCCBCAAAABBACBCBACAABCCBAABABBBBBAACABCBAACCBACBABAACACABABACBCBABBCCCACACABBBACBABCCAACBBCCABACCAAAAAAABCABAAACBCAABACBABACCAAACBAACBCABBABBACACBBCBBABCCBBCBACAAACCBA"

total_potions = calculate_potions(creature_sequence)
print("Total potions required:", total_potions)
